name: Docker Build & Push

on:
  push:
    branches:
      - main   # Trigger the workflow when you push to the main branch
  pull_request:
    branches:
      - main   # Trigger the workflow on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image for the runner

    steps:
      - name: Check out code
        uses: actions/checkout@v2   # Step to pull the code from the repository

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # Set up Docker Buildx to build multi-platform images

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build the Docker image
        run: |
          docker build -t my-ncc-website .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}   # Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}   # Docker Hub password (store as GitHub Secrets)

      - name: Push Docker image to Docker Hub
        run: |
          docker tag my-ncc-website ${{ secrets.DOCKER_USERNAME }}/my-ncc-website:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-ncc-website:latest
