name: Docker Build & Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2   # Pull code from the repository

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1   # Set up Buildx for multi-platform builds

      - name: Build the Docker image
        run: |
          echo "Building Docker image..."
          docker build -t my-ncc-website .   # Build the Docker image

      - name: Log in to Docker Hub
        uses: docker/login-action@v2   # Login to Docker Hub
        with:
          username: $naniumesh   # Docker Hub username from GitHub Secrets
          password: $NANI@umesh21   # Docker Hub password from GitHub Secrets

      - name: Tag Docker image
        run: |
          echo "Tagging Docker image..."
          docker tag my-ncc-website ${{ secrets.DOCKER_USERNAME }}/my-ncc-website:latest   # Tag the image with your username

      - name: Push Docker image to Docker Hub
        run: |
          echo "Pushing Docker image to Docker Hub..."
          docker push ${{ secrets.DOCKER_USERNAME }}/my-ncc-website:latest   # Push the image to Docker Hub
